### ISSUE TITLE
Deprecated hashing function MD5

### ISSUE THREAD

**Issue by harwoeck** [philipp-r99/NoteManager#3]
MD5 should not be used for password hashing. Instead use `bcrypt` (a password hashing function that is based on the blowfish encryption algorithm.)
 
```php
// Php:
// string password_hash(string $password, integer $algo)

$hashedPassword = password_hash(string $password, PASSWORD_BCRYPT);

```

**Comment by philipp-r99** [comment]
I know that nowadays you should never use MD5. But for our little project it's enough, because we won't publish it! If I had to choose an strong hash algorithm I would prefer SHA or AES.
But thank you anyway :)

**Comment by harwoeck** [comment]
1. I think bugs/ security issues should be fixed regardless of the size of the project. If you don't improve your project it won't get better.

2. Please inform yourself about want you are writing! Nether SHA or AES should be used. In fact you can't even use AES (Rijndael) as hashing function, because it's a encryption algorithm. And SHA is a very fast hashing function intended for hashing big data (files, etc.) in acceptable time. Bcrypt instead is a hashing function that was designed for password hashing.

Of course it's your choice what to implement.

**Comment by philipp-r99** [comment]
1. I see your point but for me it's not a big security issue. I mean if you publish it you should use strong algorithm, but that's not our purpose.
2. You are right that's true ^^, in this case Bcrypt would be perfect, but I would encrypt the sessionID with AES and a salt cos I would like to decrypt it for later usage.
